spring.messages.encoding=UTF-8
spring.application.name=vacaciones

# Conexion a la Base de Datos
spring.datasource.url=jdbc:postgresql://localhost:5432/vacaciones
spring.datasource.username=vacaciones
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraciones de Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# amplia la capacidad de los archivos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Configuracion del Task Scheduler
vacaciones.horas.escalamiento=48
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.messages.basename=messages

